### ISSUE TITLE
Error in calculation if tax is included in price

### ISSUE THREAD

**Issue by MassiveHiggsField** [CupNoodles/ti-ext-taxclasses#3]
There is an error in the way the tax is calculated if it is included in the price. If the price for example is 10€ and the tax is 7% it shows the tax as 0.7€, which is incorrect. You will need to calculate the price before tax and then add 7% to get back to 10. The correct answer here would be 0.65€ since if you add 7% to 9.35€ you will get 10€ (all a bit rounded of course). I hope i made myself clear :). 

To fix this add following lines to the file VariableTax.php in line 64 :

`        if ($this->include_in_price) {
            $tax_class->rate /= (100 + $tax_class->rate) / 100;
        }`

**Comment by CupNoodles** [comment]
Oh thank you! You're right, of course - I've put in this line and it appears to be working as expected.
